set (CMAKE_SYSTEM_NAME Generic)
set (CMAKE_C_COMPILER arm-none-eabi-gcc)
set (CMAKE_C_COMPILER_WORKS 1)
set (CMAKE_CXX_COMPILER arm-none-eabi-g++)
set (CMAKE_CXX_COMPILER_WORKS 1)
set (CMAKE_C_FLAGS "")
set (CMAKE_CXX_FLAGS "")
set (CMAKE_SIZE arm-none-eabi-size)
set (BUILD_SHARED_LIBS OFF)

